export const DATE_FORMAT = "YYYY-MM-DD"
export const shopifyApiPublicKey = process.env.SHOPIFY_API_PUBLIC_KEY || ""
export const shopifyApiSecretKey = process.env.SHOPIFY_API_SECRET_KEY || ""
export const scopes = "write_products,read_orders"
export const appUrl = process.env.SHOPIFY_APP_URL || ""
